"""
Iteration 133: Kling Storyboard 30 Frames Verification
Tests for project 06c877c953a3 - 'O cumprimento da promessa de Abraão'

Verifies:
1. GET /api/studio/projects/{id}/kling-storyboards returns total_frames=30
2. All 30 frames have text prompts (image_prompt, kling_prompt)
3. Image generation with GEMINI_API_KEY (Gemini Nano Banana)
4. Supabase bucket 'pipeline-assets' access
"""
import pytest
import requests
import os

BASE_URL = os.environ.get('REACT_APP_BACKEND_URL', '').rstrip('/')
PROJECT_ID = "06c877c953a3"  # O cumprimento da promessa de Abraão

class TestKlingStoryboards30Frames:
    """Test Kling Storyboard 30 frames for project 06c877c953a3"""
    
    @pytest.fixture(autouse=True)
    def setup(self):
        """Setup test with authentication"""
        login_response = requests.post(
            f"{BASE_URL}/api/auth/login",
            json={"email": "test@studiox.com", "password": "studiox123"}
        )
        assert login_response.status_code == 200, f"Login failed: {login_response.text}"
        self.token = login_response.json().get("access_token")
        self.headers = {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "application/json"
        }
    
    def test_01_get_kling_storyboards_returns_30_frames(self):
        """
        CRITICAL TEST: Verify project has exactly 30 frames for 5-minute video
        1 frame per 10 seconds = 30 frames for 300 seconds (5 minutes)
        """
        response = requests.get(
            f"{BASE_URL}/api/studio/projects/{PROJECT_ID}/kling-storyboards",
            headers=self.headers
        )
        
        assert response.status_code == 200, f"GET failed: {response.text}"
        data = response.json()
        
        # Verify response structure
        assert "has_storyboards" in data, "Missing has_storyboards field"
        assert "total_frames" in data, "Missing total_frames field"
        assert "total_scenes" in data, "Missing total_scenes field"
        assert "scenes" in data, "Missing scenes field"
        
        # CRITICAL: Verify 30 frames
        assert data["has_storyboards"] == True, "Project should have storyboards"
        assert data["total_frames"] == 30, f"Expected 30 frames, got {data['total_frames']}"
        
        # Verify frame count matches actual frames in scenes
        actual_frame_count = sum(len(scene.get("frames", [])) for scene in data["scenes"])
        assert actual_frame_count == 30, f"Actual frame count {actual_frame_count} != total_frames {data['total_frames']}"
        
        print(f"✅ GET returns total_frames=30 correctly")
        print(f"   - total_scenes: {data['total_scenes']}")
        print(f"   - total_frames: {data['total_frames']}")
    
    def test_02_all_30_frames_have_text_prompts(self):
        """
        Verify all 30 frames have image_prompt and kling_prompt text
        These are the textual descriptions generated by Claude
        """
        response = requests.get(
            f"{BASE_URL}/api/studio/projects/{PROJECT_ID}/kling-storyboards",
            headers=self.headers
        )
        
        assert response.status_code == 200
        data = response.json()
        
        frames_with_prompts = 0
        frames_missing_prompts = []
        
        for scene in data["scenes"]:
            for frame in scene.get("frames", []):
                frame_num = frame.get("frame_number", "?")
                has_image_prompt = bool(frame.get("image_prompt", "").strip())
                has_kling_prompt = bool(frame.get("kling_prompt", "").strip())
                
                if has_image_prompt and has_kling_prompt:
                    frames_with_prompts += 1
                else:
                    frames_missing_prompts.append({
                        "frame": frame_num,
                        "has_image_prompt": has_image_prompt,
                        "has_kling_prompt": has_kling_prompt
                    })
        
        assert frames_with_prompts == 30, \
            f"Only {frames_with_prompts}/30 frames have text prompts. Missing: {frames_missing_prompts}"
        
        print(f"✅ All 30 frames have text prompts (image_prompt + kling_prompt)")
    
    def test_03_frame_structure_is_complete(self):
        """
        Verify each frame has all required fields for Kling video generation
        """
        response = requests.get(
            f"{BASE_URL}/api/studio/projects/{PROJECT_ID}/kling-storyboards",
            headers=self.headers
        )
        
        assert response.status_code == 200
        data = response.json()
        
        required_fields = [
            "frame_number", "time_start", "time_end",
            "image_prompt", "kling_prompt", "characters_present",
            "camera_movement", "key_action", "emotion", "lighting"
        ]
        
        incomplete_frames = []
        
        for scene in data["scenes"]:
            for frame in scene.get("frames", []):
                frame_num = frame.get("frame_number", "?")
                missing_fields = [f for f in required_fields if f not in frame or not frame[f]]
                
                if missing_fields:
                    incomplete_frames.append({
                        "frame": frame_num,
                        "missing": missing_fields
                    })
        
        # Allow some flexibility - image_url may be null if generation failed
        critical_missing = [f for f in incomplete_frames 
                          if any(m in ["frame_number", "image_prompt", "kling_prompt"] 
                                for m in f["missing"])]
        
        assert len(critical_missing) == 0, \
            f"Frames missing critical fields: {critical_missing}"
        
        print(f"✅ All 30 frames have complete structure")
        if incomplete_frames:
            print(f"   Note: {len(incomplete_frames)} frames have optional fields missing")
    
    def test_04_check_image_generation_status(self):
        """
        Check how many frames have images generated vs failed
        """
        response = requests.get(
            f"{BASE_URL}/api/studio/projects/{PROJECT_ID}/kling-storyboards",
            headers=self.headers
        )
        
        assert response.status_code == 200
        data = response.json()
        
        frames_with_images = 0
        frames_with_errors = 0
        error_messages = set()
        
        for scene in data["scenes"]:
            for frame in scene.get("frames", []):
                if frame.get("image_url"):
                    frames_with_images += 1
                elif frame.get("image_error"):
                    frames_with_errors += 1
                    error_messages.add(str(frame.get("image_error", ""))[:100])
        
        print(f"📊 Image Generation Status:")
        print(f"   - Frames with images: {frames_with_images}/30")
        print(f"   - Frames with errors: {frames_with_errors}/30")
        print(f"   - Frames pending: {30 - frames_with_images - frames_with_errors}/30")
        
        if error_messages:
            print(f"   - Error types: {list(error_messages)[:3]}")
        
        # This test is informational - we don't fail if images aren't generated
        # The main requirement is that 30 frames exist with text prompts
        assert True
    
    def test_05_frame_timing_covers_5_minutes(self):
        """
        Verify frames cover the full 5-minute (300 second) duration
        Frame 1: 0:00-0:10, Frame 30: 4:50-5:00
        """
        response = requests.get(
            f"{BASE_URL}/api/studio/projects/{PROJECT_ID}/kling-storyboards",
            headers=self.headers
        )
        
        assert response.status_code == 200
        data = response.json()
        
        all_frames = []
        for scene in data["scenes"]:
            all_frames.extend(scene.get("frames", []))
        
        # Sort by frame number
        all_frames.sort(key=lambda f: f.get("frame_number", 0))
        
        # Check first frame starts at 0:00
        first_frame = all_frames[0]
        assert first_frame.get("time_start") == "0:00", \
            f"First frame should start at 0:00, got {first_frame.get('time_start')}"
        
        # Check last frame ends at or near 5:00
        last_frame = all_frames[-1]
        last_end = last_frame.get("time_end", "")
        
        # Parse time to seconds
        def parse_time(t):
            parts = t.split(":")
            if len(parts) == 2:
                return int(parts[0]) * 60 + int(parts[1])
            return 0
        
        last_end_seconds = parse_time(last_end)
        assert last_end_seconds >= 290, \
            f"Last frame should end near 5:00 (300s), got {last_end} ({last_end_seconds}s)"
        
        print(f"✅ Frames cover full 5-minute duration")
        print(f"   - First frame: {first_frame.get('time_start')} - {first_frame.get('time_end')}")
        print(f"   - Last frame: {last_frame.get('time_start')} - {last_frame.get('time_end')}")


class TestSupabaseBucketAccess:
    """Test Supabase bucket access for image storage"""
    
    @pytest.fixture(autouse=True)
    def setup(self):
        """Setup test with authentication"""
        login_response = requests.post(
            f"{BASE_URL}/api/auth/login",
            json={"email": "test@studiox.com", "password": "studiox123"}
        )
        assert login_response.status_code == 200
        self.token = login_response.json().get("access_token")
        self.headers = {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "application/json"
        }
    
    def test_06_check_supabase_bucket_error(self):
        """
        Check if Supabase bucket 'pipeline-assets' error is present
        Previous tests showed 'Bucket not found' error
        """
        response = requests.get(
            f"{BASE_URL}/api/studio/projects/{PROJECT_ID}/kling-storyboards",
            headers=self.headers
        )
        
        assert response.status_code == 200
        data = response.json()
        
        bucket_errors = 0
        for scene in data["scenes"]:
            for frame in scene.get("frames", []):
                error = str(frame.get("image_error", ""))
                if "Bucket not found" in error or "bucket" in error.lower():
                    bucket_errors += 1
        
        if bucket_errors > 0:
            print(f"⚠️ {bucket_errors}/30 frames have Supabase bucket errors")
            print(f"   This indicates 'pipeline-assets' bucket may not exist")
            print(f"   ACTION NEEDED: Create bucket in Supabase or update code to use existing bucket")
        else:
            print(f"✅ No Supabase bucket errors found")


class TestGeminiImageGeneration:
    """Test Gemini Nano Banana image generation"""
    
    @pytest.fixture(autouse=True)
    def setup(self):
        """Setup test with authentication"""
        login_response = requests.post(
            f"{BASE_URL}/api/auth/login",
            json={"email": "test@studiox.com", "password": "studiox123"}
        )
        assert login_response.status_code == 200
        self.token = login_response.json().get("access_token")
        self.headers = {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "application/json"
        }
    
    def test_07_regenerate_images_endpoint_exists(self):
        """
        Verify the regenerate-images endpoint exists
        This endpoint uses GEMINI_API_KEY to generate images
        """
        # Test with non-existent project to verify endpoint exists
        response = requests.post(
            f"{BASE_URL}/api/studio/projects/nonexistent123/kling-storyboards/regenerate-images",
            headers=self.headers,
            json={}
        )
        
        # Should return 404 for non-existent project, not 405 (method not allowed)
        assert response.status_code in [404, 400], \
            f"Unexpected status: {response.status_code}. Endpoint may not exist."
        
        print(f"✅ regenerate-images endpoint exists")


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
